<?php

    $STR_gtfs_comparison    = 'GTFS Comparison';
    $STR_compare_gtfs_data  = 'Compare GTFS Data';
    $STR_compare_head_feeds = '<p>
                        Compare two GTFS datasets step by step:
                        <ol>
                            <li>Enter here two GTFS feeds which shall be compared</li>
                            <li>On the next page, select release dates for the two GTFS feeds</li>
                            <li>Afterwards, select a route for each of the two releases</li>
                            <li>Finally, select a trip or shape for each of the two routes</li>
                        </ol>
                    </p>';
    $STR_compare_feeds      = 'Compare Feeds';
    $STR_number             = '';



    $STR_compare_gtfs_feed_versions = 'Compare GTFS Feed Versions';
    $STR_compare_head_versions = '<p>
                        Compare two GTFS datasets step by step:
                        <ol>
                            <li>Enter here two GTFS feeds and release dates which shall be compared</li>
                            <li>On the next page, select a route for each of the two GTFS feed versions</li>
                            <li>Finally, select a trip for each of the two routes</li>
                        </ol>
                    </p>';
    $STR_compare_versions   = 'Compare Versions';
    $STR_release_date_ymd   = 'Release Date<br />YYYY-MM-DD';
    $STR_empty_fileds_in    = 'Empty fields in the second line will get their value from the corresponding field in the first line.';



    $STR_compare_head_routes = '<p>
                        Compare two routes directly:
                        <ol>
                            <li>Enter here two GTFS feeds, release dates and route IDs which shall be compared</li>
                            <li>Finally, select a trip or shape for each of the two routes</li>
                        </ol>
                    </p>';




    $STR_compare_head_trips = '<p>
                        Compare two trips directly:
                        <ol>
                            <li>Enter here two GTFS feeds, release dates and trip IDs which shall be compared</li>
                        </ol>
                    </p>';



    $STR_compare_head_shapes = '<p>
                        Compare two shapes directly:
                        <ol>
                            <li>Enter here two GTFS feeds, release dates and shape IDs which shall be compared</li>
                        </ol>
                    </p>
                    <p>
                        Please note that not all GTFS feeds provide shapes.
                    </p>';
?>
