                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-routename">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Route</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Type</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://wiki.openstreetmap.org/wiki/Relation:route#Public_transport_routes" title="Proposal for OSM mapping">OSM route</a></th>
                            <th class="gtfs-date">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' and 'end_date'">Valid from</a></th>
                            <th class="gtfs-date">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' and 'end_date'">Valid until</a></th>
                            <th class="gtfs-name js-sort-routename">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' resp. 'route_desc' resp. 'route_id'">Name (resp. description, resp. Route-ID)</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Agency</a> (Network/Operator)</th>
                            <th class="gtfs-name">&#x21C5;PTNA info</th>
                        </tr>
