<?php

    $STR_invalid_input_data = 'Invalid input data';

    #
    # strings for compare.php
    #

    $STR_gtfs_comparison    = 'GTFS Comparison';
    $STR_compare_gtfs_feeds = 'Compare GTFS Feeds';
    $STR_compare_head_feeds = '<p>
                        Compare two GTFS datasets step by step:
                    </p>
                    <ol>
                        <li>Enter here (or even two) GTFS feeds which shall be compared</li>
                        <li>On the next page, select release dates for the two GTFS feeds</li>
                        <li>Afterwards, select a route for each of the two releases</li>
                        <li>Finally, select a trip or shape for each of the two routes</li>
                    </ol>';
    $STR_compare_feeds = 'Compare Feeds';
    $STR_number        = '';



    $STR_compare_gtfs_versions = 'Compare GTFS Feed Versions';
    $STR_compare_head_versions = '<p>
                        Compare two GTFS datasets step by step:
                    </p>
                    <ol>
                        <li>Enter here GTFS feeds and release dates which shall be compared</li>
                        <li>On the next page, select a route for each of the two GTFS feed versions</li>
                        <li>Finally, select a trip for each of the two routes</li>
                    </ol>';
    $STR_compare_versions    = 'Compare Versions';
    $STR_release_date        = 'Release Date';
    $STR_release_date_legend = 'Release Date: YYYY-MM-DD or "latest" or "previous" or "long-term"';
    $STR_empty_fields_in     = 'Empty fields in the second line will get their value from the corresponding field in the first line.';



    $STR_compare_gtfs_routes = 'Compare GTFS Routes';
    $STR_compare_head_routes = '<p>
                        Compare two routes directly:
                    </p>
                    <ol>
                        <li>Enter here GTFS feeds, release dates and route IDs which shall be compared</li>
                        <li>Finally, select a trip or shape for each of the two routes</li>
                    </ol>';
    $STR_compare_routes = 'Compare Routes';




    $STR_compare_gtfs_trips = 'Compare GTFS Trips';
    $STR_compare_head_trips = '<p>
                        Compare two trips directly:
                    </p>
                    <ol>
                        <li>Enter here GTFS feeds, release dates and trip IDs which shall be compared</li>
                    </ol>';
    $STR_compare_trips = 'Compare Trips';



    $STR_compare_gtfs_shapes = 'Compare GTFS Shapes';
    $STR_compare_head_shapes = '<p>
                        Compare two shapes directly:
                    </p>
                    <ol>
                        <li>Enter here GTFS feeds, release dates and shape IDs which shall be compared</li>
                    </ol>
                    <p>
                        Please note that not all GTFS feeds provide shapes.
                    </p>';
    $STR_compare_shapes = 'Compare Shapes';

    #
    # strings for compare-routes.php
    #


?>
