                <p>
                    The first column contains a link to the analysis of the <a href="/en/gtfs-doc.php#gtfsdata">GTFS data</a>.
                    A calendar icon indicates that the previous version of the GTFS data is available as well.
                </p>
                <p>
                    The <a href="/en/gtfs-doc.php#download">update</a> of the data on this page occurs at irregular intervals.
                </p>
