    <table id="message-table">
        <thead>
            <tr class="message-tableheaderrow">
                <th class="message-text">Message</th>
                <th class="message-type">Type</th>
                <th class="message-option">Option</th>
                <th class="message-description">Description</th>
                <th class="message-fix">How to fix</th>
                <th class="message-image">Image</th>
            </tr>
        </thead>
        <tbody>
            <tr class="message-tablerow">
                <td class="message-text">'colour' has unknown value '%s'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'colour' of Route does not fit to 'colour' of Route-Master: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'colour' of Route is not set but 'colour' of Route-Master is set: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'colour' of Route is set but 'colour' of Route-Master is not set: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'name' is not set</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s' includes the separator value ';' (semi-colon) with sourrounding blank</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s' of Route does not fit to 'network' = '%s' of Route-Master: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s' should be long form</td>
                <td class="message-type">Notes</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s' should be short form</td>
                <td class="message-type">Notes</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s': ',' (comma) as separator value should be replaced by ';' (semi-colon) without blank</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' is not set</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network:long' is long form</td>
                <td class="message-type">Notes</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network:long' matches long form</td>
                <td class="message-type">Notes</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'public_transport:version' is neither '1' nor '2'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'public_transport:version' is not set</td>
                <td class="message-type">Notes</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'public_transport:version' is not set to '2'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'ref' is not set</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'route' = '%s' of Route does not fit to 'route_master' = '%s' of Route-Master: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'route' tag is not set: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'type' = '%s' is not 'route': %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'type' tag is not set: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Error in input data: insufficient data for nodes</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Error in input data: insufficient data for ways</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Missing route for ref='%s' and route='%s'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Multiple Routes but 'public_transport:version' is not set to '2'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Multiple Routes but no Route-Master</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Multiple Routes but this Route is not a member of any Route-Master</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: '%s' is not part of 'name' (derived from '%s' = '%s')</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'from' is not set</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'name' has more than one '=>' but 'via' is not set</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'name' includes deprecated '&lt;=&gt;'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'name' includes deprecated '==&gt;'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'name' of Route is identical to 'name' of other Route(s), consider setting an appropriate 'via' value and include that into 'name'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'name' should (at least) be of the form '... ref ...: from => to'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'name' should be similar to the form '... ref ...: from => to'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name-relaxed</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'public_transport' = 'platform' is part of way</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'public_transport' = 'stop_position' is not part of way</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'ref' is not part of 'name'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'role' = '%s' and %s: consider setting 'public_transport' = 'platform'</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--ptv1-compatibility=show</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'role' = '%s' and %s: consider setting 'public_transport' = 'stop_position'</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--ptv1-compatibility=show</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'role' = '%s' but 'public_transport' is not set</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'to' is not set</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'via' is set: %d. via-part ('%s') of 'name' is not equal to %d. via-value = '%s'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: 'via' is set: %d. via-part ('%s') of 'name' is not part of %d. via-value = '%s'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name-relaxed</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: consider removing the first way of the route from the relation, it is a way before the first stop position: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: consider removing the last way of the route from the relation, it is a way after the last stop position: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: empty 'role'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: first node of oneway way has 'role' = 'stop_exit_only'</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: first node of way has 'role' = 'stop_exit_only'. Is the route sorted in reverse order?</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: first node of way is not a stop position of this route: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: first node of way is not the first stop position of this route: %s versus %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: first stop position on first way is not the first stop position of this route: %s versus %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: first way is a oneway road and ends in a 'stop_position' of this route and there is no exit. Is the route sorted in reverse order?</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: from-part ('%s') of 'name' is not equal to 'from' = '%s'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: from-part ('%s') of 'name' is not part of 'from' = '%s'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name-relaxed</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: has a gap, consists of %d segments. Gap appears at way</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: includes %d entire roundabout but uses only segments</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-sequence<br />--check-roundabout</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: incorrect order of 'stop_position', 'platform' and 'way' (stop/platform after way)</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: last node of oneway way has 'role' = 'stop_entry_only'</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: last node of way has 'role' = 'stop_entry_only'. Is the route sorted in reverse order?</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: last node of way is not a stop position of this route: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: last node of way is not the last stop position of this route: %s versus %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: last stop position on last way is not the last stop position of this route: %s versus %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: mismatch between 'role' = '%s' and 'public_transport' = '%s'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: missing '%s' = 'yes' on 'public_transport' = 'stop_position'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: roundabout appears twice, following itself</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: there are less via-parts in 'name' (%d) than in 'via' (%d)</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: there are more via-parts in 'name' (%d) than in 'via' (%d)</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: there are no 'public_transport' = 'stop_position' and no 'public_transport' = 'platform'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: there is no 'public_transport' = 'platform'</td>
                <td class="message-type">Notes</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: there is no 'public_transport' = 'stop_position'</td>
                <td class="message-type">Notes</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: there is no stop position of this route on the first way: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: there is no stop position of this route on the last way: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: there is only one 'public_transport' = 'platform'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: there is only one 'public_transport' = 'stop_position'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: to-part ('%s') of 'name' is not equal to 'to' = '%s'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: to-part ('%s') of 'name' is not part of 'to' = '%s'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-name-relaxed</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: using motorway_link way without entering a motorway way</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-motorway-link</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: using oneway way in wrong direction</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-sequence</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 route: wrong 'role' = '%s'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route does not exist in the given data set: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route exists in the given data set but 'ref' tag is not set: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route has 'network' = '%s' value which is considered as not relevant: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route has 'operator' = '%s' value which is considered as not relevant: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route has 'route' = '%s' value which is considered as not relevant: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route has different 'network' = '%s' than Route-Master 'network' = '%s': %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route has different 'operator' = '%s' than Route-Master 'operator' = '%s': %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route has different 'ref' = '%s' than Route-Master 'ref' = '%s' - this should be avoided: %s</td>
                <td class="message-type">Notes</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route has different 'route' = '%s' than Route-Master 'route_master' = '%s': %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route has not matching 'ref' = '%s': %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route is not member of Route-Master: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route might be listed with 'ref' = '%s' in a different section or in section 'Not clearly assigned routes' of this analysis: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route with Relation(s)</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route with only 1 Node</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route with only 1 Way</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route without Node(s)</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route without Way(s)</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master has less Routes than actually match (%d versus %d) in the given data set</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master has more Routes than actually match (%d versus %d) in the given data set</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master has not matching 'ref' = '%s': %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master might be listed with 'ref' = '%s' in a different section or in section 'Not clearly assigned routes' of this analysis: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master might be listed with unknown 'ref' in section 'Public Transport Lines without 'ref'' of this analysis: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master with Node(s)</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master with Relation(s) unequal to 'route'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master with Way(s)</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master without Route(s)</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Type is not set. Line %s of Routes-Data. Contents of line: '%s'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Type is not supported: '%s'. Line %s of Routes-Data. Contents of line: '%s'</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: '%s' = '%s' of stop should be deleted, 'route_ref' = '%s' exists</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-route-ref</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: '%s' = '%s' of stop should be replaced by 'route_ref' = '%s'</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-route-ref</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'highway' = 'bus_stop' is set on way. Allowed on nodes only!</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-bus-stop</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'ref' = '%s' of stop should represent the reference of the stop, but includes the 'ref' = '%s' of this route %s</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-route-ref</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'route_ref' = '%s' of stop does not include 'ref' = '%s' value of this route%s</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-route-ref</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'route_ref' = '%s' of stop includes the separator value ';' (semi-colon) with sourrounding blank</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-route-ref</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'route_ref' = '%s' of stop: ',' (comma) as separator value should be replaced by ';' (semi-colon) without blank</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-route-ref</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: restricted access (%s) to way without 'psv'='yes', '%s'='yes', '%s'='designated', or ...</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-access</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: restricted access at barrier (%s) without 'psv'='yes', '%s'='yes', '%s'='designated', or ...</td>
                <td class="message-type">Errors</td>
                <td class="message-option">--check-access</td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: unclear access (%s) to way</td>
                <td class="message-type">Notes</td>
                <td class="message-option">--check-access</td>
                <td class="message-description">A conditional access is mapped to a way. PTNA will not analyze the value of the tag.<br />Example: 'psv:conditional=yes @ (Mo-Fr 05:00-22:00)'.</td>
                <td class="message-fix">Please evaluate the value manually.</td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Skipping further analysis ...</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">The tag 'line' (='%s') is reserved for 'power' = 'line' related tagging. For public transport 'route_master' and 'route' are used.</td>
                <td class="message-type">Notes</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">There is more than one Route-Master</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">This Route is direct member of more than one Route-Master: %s</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">This Route is not a member of any Route-Master</td>
                <td class="message-type">Errors</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
        </tbody>
    </table>
