<tr class="statistics-tableheaderrow">
    <th class="statistics-name js-sort-none" colspan="1" >Network</th>
    <th class="statistics-date js-sort-none" colspan="3">Timezone</th>
    <th class="statistics-date js-sort-none" colspan="1">OSM Data</th>
    <th class="statistics-date js-sort-none" colspan="3">Download</th>
    <th class="statistics-date js-sort-none" colspan="1">Routes Data</th>
    <th class="statistics-date js-sort-none" colspan="3">Analysis</th>
</tr>
<tr class="statistics-tableheaderrow">
    <th class="statistics-name js-sort-string">Name&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-name js-sort-string">UTC +/-&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-name js-sort-string">Abbr.&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-name js-sort-string">Name&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-date js-sort-string">As Of&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-date js-sort-string">Started&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-duration js-sort-number">Duration [h:m:s]&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-size js-sort-number">Size [MB]&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-date js-sort-string">Last Modified&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-date js-sort-string">Started&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-duration js-sort-number">Duration [h:m:s]&nbsp;&nbsp;&nbsp;&nbsp;</th>
    <th class="statistics-date js-sort-number">Changes&nbsp;&nbsp;&nbsp;&nbsp;</th>
</tr>
