<tr class="statistics-tableheaderrow">
    <th class="statistics-name" rowspan="2">Name</th>
    <th class="statistics-date" colspan="3">Download</th>
    <th class="statistics-date" colspan="2">Analysis</th>
</tr>
<tr class="statistics-tableheaderrow">
    <th class="statistics-date">Started</th>
    <th class="statistics-duration">Duration [h:m:s]</th>
    <th class="statistics-size">Size [MB]</th>
    <th class="statistics-date">Started</th>
    <th class="statistics-duration">Duration [h:m:s]</th>
</tr>

