<tr class="statistics-tableheaderrow">
    <th class="statistics-name" rowspan="2">Name</th>
    <th class="statistics-date" colspan="3">Download</th>
    <th class="statistics-date" colspan="1">Routes Data</th>
    <th class="statistics-date" colspan="3">Analysis</th>
</tr>
<tr class="statistics-tableheaderrow">
    <th class="statistics-date">Started</th>
    <th class="statistics-duration">Duration [h:m:s]</th>
    <th class="statistics-size">Size [MB]</th>
    <th class="statistics-date">Last Modified</th>
    <th class="statistics-date">Started</th>
    <th class="statistics-duration">Duration [h:m:s]</th>
    <th class="statistics-date">Has Changes</th>
</tr>
