                    <tr class="results-tableheaderrow">
                        <th class="results-name"rowspan="2">Name</th>
                        <th class="results-name" colspan="6">GTFS Daten</th>
                        <th class="results-name" colspan="4">OSM / PTNA Daten</th>
                    </tr>
                    <tr class="results-tableheaderrow">
                        <th class="results-network">Verkehrsverbund (Eigentümer)</th>
                        <th class="results-datadate">Gültig ab</th>
                        <th class="results-datadate">Gültig bis</th>
                        <th class="results-datadate">Version</th>
                        <th class="results-datadate">Aktualisiert am</th>
                        <th class="results-network">Lizenz des Verkehrsverbundes</th>
                        <th class="results-network">Lizenz Freigabe für OSM</th>
                        <th class="results-datadate"><a href="/de/gtfs-doc.php#prepared">Bearbeitet am</a></th>
                        <th class="results-datadate"><a href="/de/gtfs-doc.php#aggregated">Aggregiert</a></th>
                        <th class="results-datadate"><a href="/de/gtfs-doc.php#normalized">Normalisiert</a></th>
                    </tr>
