                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-routeshortname"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Linie</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Typ</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://wiki.openstreetmap.org/wiki/DE:%C3%96ffentlicher_Verkehr#Tags_in_der_Relation_zur_Erfassung_von_Verkehrslinien_und_Kursen_sind:" title="Vorschlag für OSM mapping">OSM route</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gültig von</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gültig bis</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' bzw. 'route_desc' bzw. 'route_id'">Name (bzw. Beschreibung, bzw. Route-ID)</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Agency</a> (Network/Operator)&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name">PTNA Info&nbsp;&nbsp;&nbsp;&nbsp;</th>
                        </tr>
