                    <tr class="results-tableheaderrow">
                        <th class="results-datadate" colspan="5">Haltestellen</th>
                        <th class="results-datadate" colspan="3">PTNA</th>
                    </tr>
                    <tr class="results-tableheaderrow">
                        <th class="results-name">Nummer</th>
                        <th class="results-name">Name</th>
                        <th class="results-name">Latitute</th>
                        <th class="results-name">Longitude</th>
                        <th class="results-name">Stop-ID</th>
                        <th class="results-datadate">Ungültig</th>
                        <th class="results-datadate">Fehlerhaft</th>
                        <th class="results-network">Kommentar</th>
                    </tr>

