                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" colspan="5">Haltestellen</th>
                            <th class="gtfs-name" colspan="3">PTNA</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name">Nummer</th>
                            <th class="gtfs-name">Name</th>
                            <th class="gtfs-number">Latitude</th>
                            <th class="gtfs-number">Longitude</th>
                            <th class="gtfs-text">Stop-ID</th>
                            <th class="gtfs-checkbox">Ungültig</th>
                            <th class="gtfs-checkbox">Fehlerhaft</th>
                            <th class="gtfs-comment">Kommentar</th>
                        </tr>
