                <p>
                    Die erste Spalte der Tabelle enthält jeweils einen Link auf eine Auswertung der <a href="/de/gtfs-doc.php#gtfsdata">GTFS-Daten</a>.
                    Ein Kalendersymbol (<img src="/img/Calendar19.png" />) zeigt an, dass die vorherige Version der GTFS-Daten ebenfalls verfügbar ist.
                    Ein anderes Symbol (<img src="/img/long-term19.png" />) zeigt an, dass eine Langzeitversion der GTFS-Daten ebenfalls verfügbar ist.
                    Das ist in der Regel die Version der GTFS-Daten zum letzten offiziellen Fahrplanwechsel.
                </p>
                <p>
                    Die <a href="/de/gtfs-doc.php#download">Aktualisierung</a> der Daten auf dieser Seite erfolgt in unregelmäßigen Abständen.
                </p>
