                            <tr class="gtfs-tableheaderrow">
                                <th class="gtfs-name js-sort-routename">&#x21C5Linie</th>
                                <th class="gtfs-name">&#x21C5OSM route</th>
                                <th class="gtfs-name">&#x21C5PTNA</th>
                                <th class="gtfs-name">&#x21C5Information</th>
                            </tr>
