                        <div style="border: 1px dotted gray; border-radius: 5px; padding: 0.5em;">
                                Legende:                                &nbsp;
                                                                        </nobr><img src="/img/long-term19.png" width="19px" height="19px" title="long-term" />&nbsp;
                                Langzeitversion (long-term)             </nobr>&nbsp;/&nbsp;
                                                                        </nobr><img src="/img/previous.svg" width="19px" height="19px" title="previous" />&nbsp;
                                Vorgängerversion (previous)             </nobr>&nbsp;/&nbsp;<nobr>
                                                                        </nobr><img src="/img/CheckMark.png" width="19px" height="19px" title="previous" />&nbsp;
                                PTNAs aktuellste Version                </nobr>&nbsp;/&nbsp;<nobr>
                                                                        </nobr><img src="/img/error.svg" width="19px" height="19px" title="previous" />&nbsp;
                                Version mit Fehlern                     </nobr>&nbsp;/&nbsp;<nobr>
                                yyyy-mm-dd                              &nbsp;
                                Datum der Version                       </nobr>&nbsp;/&nbsp;
                                                                        <nobr><span style="background-color: limegreen;">
                                yyyy-mm-dd</span>                       &nbsp;
                                Angezeigte Version                      </nobr>&nbsp;/&nbsp;
                                                                        <nobr><span style="background-color: lightgray; text-decoration: line-through;">
                                yyyy-mm-dd</span>                       &nbsp;
                                Fehlende Version                        </nobr>
                        </div>
