                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Linie</a></th>
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Typ</a></th>
                            <th class="gtfs-date" colspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gültigkeit</a></th>
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' bzw. 'route_desc' bzw. 'route_id'">Name (bzw. Beschreibung, bzw. Route-ID)</a></th>
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Agency</a> (Network/Operator)</th>
                            <th class="gtfs-name" colspan="3">PTNA Info zur Linie</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-date">Von</th>
                            <th class="gtfs-date">Bis</th>
                            <th class="gtfs-checkbox">Ungültig</th>
                            <th class="gtfs-checkbox">Fehlerhaft</th>
                            <th class="gtfs-comment">Kommentar</th>
                        </tr>
