                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2">Name</th>
                            <th class="gtfs-text" rowspan="2">Verbund / Abdeckung</th>
                            <th class="gtfs-name" colspan="6">GTFS Daten</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-text"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_publisher_name' bzw. PTNA: 'ptna' - 'feed_publisher_name'">Herausgeber</a> (Eigentümer)</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_start_date'">Gültig ab</a></th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_end_date'">Gültig bis</a></th>
                            <th class="gtfs-number"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_version'">Version</a></th>
                            <th class="gtfs-date">Aktualisiert</th>
                            <th class="gtfs-text">Details (Lizenzen, ...)</th>
                        </tr>
