                <p>
                    Die erste Spalte der Tabelle enthält jeweils einen Link auf eine Auswertung der <a href="/de/gtfs-doc.php#gtfsdata">GTFS-Daten</a>.
                    <ul style="list-style: none;">
                        <li> <img src="/img/long-term19.png" /> : zeigt an, dass eine Langzeitversion der GTFS-Daten ebenfalls verfügbar ist.
                             Das ist in der Regel die Version der GTFS-Daten zum letzten offiziellen Fahrplanwechsel.</li>
                        <li> <img src="/img/previous.svg" width="19px" height="19px"/> : zeigt an, dass eine vorherige Version der GTFS-Daten ebenfalls verfügbar ist.</li>
                        <li> <img src="/img/compare19.png" width="19px" height="19px"/> : zeigt an, dass man zwei Versionen vergleichen kann (Beta-Status: noch nicht bis ins Detail realisiert)</li>
                    </ul>
                </p>
                <p>
                    Die GTFS-Daten werden nahezu täglich auf <a href="/de/gtfs-doc.php#download">Aktualität</a> geprüft.
                    Jedoch wird nicht jede verfügbare neue Version hier analysiert und bereit gestellt - das würde den Speicherplatz zu sehr belasten.
                    In der Spalte "Details (Lizenzen, ...)" kann die Liste der verfügbaren GTFS-Daten abgerufen werden.
                </p>
