                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name"    rowspan="2">Variante</th>
                            <th class="gtfs-name"    rowspan="2">Trip-ID</th>
                            <th class="gtfs-comment" rowspan="2">Anzahl Fahrten</th>
                            <th class="gtfs-name"    colspan="2">Gültigkeit</th>
                            <th class="gtfs-name"    colspan="3">Haltestellen</th>
                            <th class="gtfs-comment" colspan="1">PTNA Info</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-date">Von</th>
                            <th class="gtfs-date">Bis</th>
                            <th class="gtfs-text">Start</th>
                            <th class="gtfs-text">Über</th>
                            <th class="gtfs-text">Ende</th>
                            <th class="gtfs-comment">Kommentar</th>
                        </tr>
