                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2">Name</th>
                            <th class="gtfs-name" colspan="6">GTFS Daten</th>
                            <th class="gtfs-name" colspan="4">OSM / PTNA Daten</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-text"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS spec: 'feed_info.txt' - 'feed_publisher_name' bzw. PTNA: 'ptna' - 'feed_publisher_name'">Herausgeber</a> (Eigentümer)</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS spec: 'feed_info.txt' - 'feed_start_date'">Gültig ab</a></th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS spec: 'feed_info.txt' - 'feed_end_date'">Gültig bis</a></th>
                            <th class="gtfs-number"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS spec: 'feed_info.txt' - 'feed_version'">Version</a></th>
                            <th class="gtfs-date">Aktualisiert</th>
                            <th class="gtfs-text">Lizenz des Herausgebers</th>
                            <th class="gtfs-text">Lizenz Freigabe für OSM</th>
                            <th class="gtfs-date"><a href="/de/gtfs-doc.php#prepared">Bearbeitet</a></th>
                            <th class="gtfs-date"><a href="/de/gtfs-doc.php#aggregated">Aggregiert</a></th>
                            <th class="gtfs-date"><a href="/de/gtfs-doc.php#normalized">Normalisiert</a></th>
                        </tr>
