        <footer id="footer-de">
            <p>
                Alle GTFS-Daten © Eigentümer der GTFS-Daten.
            </p>
            <p>
                Alle geografischen Daten <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap Mitwirkende</a>.
            </p>
            <p>
                Dieses Programm ist freie Software: Sie können es weitergeben und/oder ändern es unter den Bedingungen der <a href="https://www.gnu.org/licenses/gpl.html"> GNU GENERAL PUBLIC LICENSE, Version 3,  29. Juni 2007</a>, wie von der Free Software Foundation veröffentlicht, entweder Version 3 der Lizenz oder (nach Ihrer Wahl) eine spätere Version.
                Den Quellcode erhalten Sie über <a href="https://github.com/osm-ToniE"> GitHub </a>.
            </p>
        </footer>
