                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-routename">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Linie</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Typ</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://wiki.openstreetmap.org/wiki/DE:%C3%96ffentlicher_Verkehr#Tags_in_der_Relation_zur_Erfassung_von_Verkehrslinien_und_Kursen_sind:" title="Vorschlag für OSM mapping">OSM route</a></th>
                            <th class="gtfs-date">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gültig von</a></th>
                            <th class="gtfs-date">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gültig bis</a></th>
                            <th class="gtfs-name js-sort-routename">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' bzw. 'route_desc' bzw. 'route_id'">Name (bzw. Beschreibung, bzw. Route-ID)</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Agency</a> (Network/Operator)</th>
                            <th class="gtfs-name">&#x21C5;PTNA Info</th>
                        </tr>
