                    <tr class="results-tableheaderrow">
                        <th class="results-datadate" rowspan="2">Linie</th>
                        <th class="results-datadate" colspan="3">Haltestellen</th>
                        <th class="results-datadate" colspan="3">PTNA</th>
                    </tr>
                    <tr class="results-tableheaderrow">
                        <th class="results-datadate">Start</th>
                        <th class="results-datadate">Über</th>
                        <th class="results-datadate">Ende</th>
                        <th class="results-datadate">Ungültig</th>
                        <th class="results-datadate">Fehlerhaft</th>
                        <th class="results-name">Kommentar</th>
                    </tr>

