    <table id="message-table">
        <thead>
            <tr class="message-tableheaderrow">
                <th class="message-text">Meldung</th>
                <th class="message-type">Typ</th>
                <th class="message-option">Option</th>
                <th class="message-description">Beschreibung</th>
                <th class="message-fix">Wie zu korrigieren</th>
                <th class="message-image">Bild</th>
            </tr>
        </thead>
        <tbody>
            <tr class="message-tablerow">
                <td class="message-text">'colour' der Route ist gesetzt aber 'colour' des Route-Masters ist nicht gesetzt: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'colour' der Route ist nicht gesetzt aber 'colour' des Route-Masters ist gesetzt: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'colour' der Route passt nicht zu 'colour' des Route-Masters: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'colour' hat einen unbekannten Wert '%s'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'name' ist nicht gesetzt</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s' der Route passt nicht zu 'network' = '%s' des Route-Masters: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s' enthält das Trennzeichen ';' (Semikolon) mit umgebendem Leerzeichen</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s' sollte in Kurzform angegeben werden</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s' sollte in Langform angegeben werden</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' = '%s': ',' (Komma) als Trennzeichen sollte durch ';' (Semikolon, ohne Leerzeichen) ersetzt werden</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network' ist nicht gesetzt</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network:long' ist Langform</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'network:long' passt zur Langform</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'public_transport:version' ist nicht '2'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'public_transport:version' ist nicht gesetzt</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'public_transport:version' ist weder '1' noch '2'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'ref' ist nicht gesetzt</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'route' = '%s' der Route passt nicht zu 'route_master' = '%s' des Route-Masters: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'route' ist nicht gesetzt: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'type' = '%s' ist nicht 'route': %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">'type' ist nicht gesetzt: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Das Tag 'line' (='%s') ist reserviert für 'power' = 'line' spezifisches Tagging. Für Public Transport werden 'route_master' und 'route' genutzt. </td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Die Route ist direktes Element von mehr als einem Route-Master: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Diese Route ist nicht Element eines existierenden Route-Masters</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Es existiert mehr als ein Route-Master</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Fahrzeugtyp ist nicht definiert. Zeile %s der Routen-Daten. Inhalt der Zeile: '%s'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Fahrzeugtyp wird nicht unterstützt: '%s'. Zeile %s der Routen-Daten. Inhalt der Zeile: '%s'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Fehlende Linie für 'ref' = '%s' und 'route' = '%s'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Fehler in den Inputdaten: nicht genügend Daten für 'nodes'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Fehler in den Inputdaten: nicht genügend Daten für 'ways'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Mehrere Routen aber 'public_transport:version' ist nicht auf '2' gesetzt</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Mehrere Routen aber diese Route ist nicht Element eines existierenden Route-Masters</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Mehrere Routen aber kein Route-Master</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: '%s' ist nicht Teil von 'name' (hergeleitet von '%s' = '%s')</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'from' ist nicht gesetzt</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'name' der Route ist identisch zu 'name' anderer Route(n). Setze gegebenenfalls einen passenden 'via' Wert und nehme ihn in 'name' auf.</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'name' enthält mehr als ein '=>', aber 'via' ist nicht gesetzt</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'name' enthält unübliches '&lt;=&gt;'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'name' enthält unübliches '==&gt;'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'name' sollte (mindest) von der Form '... ref ...: from => to' sein</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'name' sollte annähernd die Form '... ref ...: from => to' haben</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'public_transport' = 'platform' liegt auf dem Fahrweg</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'public_transport' = 'stop_position' liegt nicht auf dem Fahrweg</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'ref' ist nicht Teil von 'name'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'role' = '%s' aber 'public_transport' ist nicht gesetzt</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'role' = '%s' und %s: 'public_transport' = 'platform' sollte gesetzt werden</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'role' = '%s' und %s: 'public_transport' = 'stop_position' sollte gesetzt werden</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'to' ist nicht gesetzt</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'via' ist gesetzt: der %d. 'Über'-Anteil ('%s') von 'name' ist nicht Teil von %d. via-Teil = '%s'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: 'via' ist gesetzt: der %d. 'Über'-Anteil ('%s') von 'name' ist nicht gleich dem %d. via-Teil = '%s'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: Einbahnstraße wird in der falschen Richtung benutzt</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: Konflikt zwischen 'role' = '%s' und 'public_transport' = '%s'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: Kreisverkehr tritt doppelt auf, direkt nach sich selbst</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: befährt %d kompletten Kreisverkehr von dem aber nur Teile benutzt werden</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der 'Nach'-Anteil ('%s') von 'name' ist nicht Teil von 'to' = '%s'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der 'Nach'-Anteil ('%s') von 'name' ist nicht identisch zu 'to' = '%s'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der 'Von'-Anteil ('%s') von 'name' ist nicht Teil von 'from' = '%s'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der 'Von'-Anteil ('%s') von 'name' ist nicht identisch zu 'from' = '%s'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der erste Punkt des Fahrweges hat die 'role' = 'stop_exit_only'. Sind die Wege der Route falsch herum sortiert?</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der erste Punkt des Fahrweges ist nicht die erste 'stop_position' der Route: %s gegenüber %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der erste Punkt des Weges ist keine 'stop_position' dieser Route: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der erste Punkt einer Einbahnstraße hat die 'role' = 'stop_exit_only'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der erste Weg ist eine Einbahnstraße und endet in einer 'stop_position' und es geht nicht mehr weiter. Sind die Wege der Route falsch herum sortiert?</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der letzte Punkt des Fahrweges hat die 'role' = 'stop_entry_only'. Sind die Wege der Route falsch herum sortiert?</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der letzte Punkt des Fahrweges ist nicht die letzte 'stop_position' der Route: %s gegenüber %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der letzte Punkt des Weges ist keine 'stop_position' dieser Route: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: der letzte Punkt einer Einbahnstraße hat die 'role' = 'stop_entry_only'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: die erste 'stop_position' auf dem ersten Weg ist nicht die erste 'stop_position' der Route: %s gegenüber %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: die letzte 'stop_position' auf dem letzten Weg ist nicht die letzte 'stop_position' der Route: %s gegenüber %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: entferne gegebenenfalls den ersten Weg des Fahrweges aus der Relation, es ist ein Weg vor der ersten 'stop_position': %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: entferne gegebenenfalls den letzten Weg des Fahrweges aus der Relation, es ist ein Weg nach der letzten 'stop_position': %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es gibt keine 'public_transport' = 'platform'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es gibt keine 'public_transport' = 'stop_position'</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es gibt keine 'public_transport' = 'stop_position' und keine 'public_transport' = 'platform'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es gibt keine 'stop_position' auf dem ersten Weg der Route: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es gibt keine 'stop_position' auf dem letzten Weg der Route: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es gibt mehr 'Über'-Anteile in 'name (%d) als in 'via' (%d)</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es gibt nur eine 'public_transport' = 'platform'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es gibt nur eine 'public_transport' = 'stop_position'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es gibt weniger 'Über'-Anteile in 'name (%d) als in 'via' (%d)</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: es wird eine 'motorway_link' Straße benutzt ohne vorher oder nachher eine 'motorway' Straße benutzt zu haben</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: falsche 'role' = '%s'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: falsche Reihenfolge von 'stop_position', 'platform' und 'way': 'stop_position'/'platform' müssen vor allen 'way' kommen</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: fehlende Angabe '%s' = 'yes' an 'public_transport' = 'stop_position'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: hat eine Lücke, besteht aus %d Segmenten. Die Lücke ist bei dem Weg</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">PTv2 Route: leere 'role'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route existiert im geladenen Datensatz, 'ref' ist aber nicht gesetzt: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route hat einen 'network' = '%s' Wert, der als irrelevant betrachtet wird: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route hat einen 'operator' = '%s' Wert, der als irrelevant betrachtet wird: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route hat einen 'route' = '%s' Wert, der als irrelevant betrachtet wird: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route hat einen anderen 'network' = '%s' Wert als der Route-Master 'network' = '%s': %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route hat einen anderen 'operator' = '%s' Wert als der Route-Master 'operator' = '%s': %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route hat einen anderen 'ref' = '%s' Wert als der Route-Master 'ref' = '%s - das sollte vermieden werden': %s</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route hat einen anderen 'route' = '%s' Wert als der Route-Master 'route' = '%s': %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route hat unpassenden 'ref' = '%s' Wert: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route ist nicht Element des Route-Masters: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route ist unter der 'ref' = '%s' möglicherweise in einem anderen Abschnitt oder im Abschnitt 'Nicht eindeutig zugeordnete Linien' gelistet: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route mit Relation(en)</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route mit nur einem Node</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route mit nur einem Way</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route ohne Node(s)</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route ohne Way(s)</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route wurde im geladenen Datensatz nicht gefunden: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master hat mehr Routen als im Datensatz tatsächlich passend gefunden wurden (%d gegenüber %d)</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master hat unpassenden  'ref' = '%s' Wert: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master hat weniger Routen als im Datensatz tatsächlich passend gefunden wurden (%d gegenüber %d)</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master ist mit undefiniertem 'ref' Wert möglicherweise im Abschnitt 'ÖPNV Linien ohne 'ref'-Wert' gelistet: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master ist unter der selben 'ref' = '%s' möglicherweise in einem anderen Abschnitt oder im Abschnitt 'Nicht eindeutig zugeordnete Linien' gelistet: %s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master mit Node(s)</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master mit Relation(en) ungleich 'route'</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master mit Way(s)</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route-Master ohne Route(n)</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: '%s' = '%s' der Haltestelle sollte durch 'route_ref' = '%s' ersetzt werden</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: '%s' = '%s' der Haltestelle sollte gelöscht werden, 'route_ref' = '%s' existiert</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'highway' = 'bus_stop' ist auf einem 'way' gesetzt. Dieses Tag ist nur auf Nodes erlaubt.</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'ref' = '%s' der Haltestelle sollte die Referenz der Haltestelle sein, enthält aber die 'ref' = '%s' dieser Route %s</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'route_ref' = '%s' der Haltestelle enthält das Trennzeichen ';' (Semikolon) mit umgebendem Leerzeichen</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'route_ref' = '%s' der Haltestelle enthält nicht den 'ref' = '%s' Wert dieser Route%s</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: 'route_ref' = '%s' der Haltestelle: ',' (Komma) als Trennzeichen sollte durch ';' (Semikolon, ohne Leerzeichen) ersetzt werden</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: eingeschränkte Befahrbarkeit (%s) auf Weg ohne dass 'psv' = 'yes', '%s' = 'yes', '%s' = 'designated', oder ... angegeben ist</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: eingeschränkte Befahrbarkeit an Barriere (%s) ohne dass 'psv' = 'yes', '%s' = 'yes', '%s' = 'designated', oder ... angegeben ist</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Route: unklare Befahrbarkeit (%s) auf Weg</td>
                <td class="message-type">Anmerkungen</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
            <tr class="message-tablerow">
                <td class="message-text">Weitere Analyse wird übersprungen ...</td>
                <td class="message-type">Fehler</td>
                <td class="message-option"></td>
                <td class="message-description"></td>
                <td class="message-fix"></td>
                <td class="message-image"></td>
            </tr>
        </tbody>
    </table>
