        <footer id="footer-sl" class="clearing">
            <p>
                Vsi geografski podatki <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap contributors</a>.
            </p>
            <p>
                Ta program je prosta programska oprema: lahko ga razširjate in/ali spreminjate pod pogoji <a href="https://www.gnu.org/licenses/gpl.html">GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007</a> kot jo je objavila fundacija Free Software Foundation, bodisi različica 3 licence bodisi (po vaši izbiri) katera koli poznejša različica. Izvorno kodo dobite prek <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
            <p>
                PTNA uporablja <a href="https://wiki.openstreetmap.org/wiki/Overpass_API" title="Overpass-API">Overpass-API</a> za prenos podatkov iz sistema OSM. Storitev Overpass-API zagotavlja <a href="https://kumi.systems" title="Kumi Systems">Kumi Systems (Graz, Austria)</a>, hvala za podporo.
            </p>
        </footer>
