                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2">Name</th>
                            <th class="gtfs-text" rowspan="2">Network / Operator / Coverage</th>
                            <th class="gtfs-name" colspan="7">GTFS data</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-text"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_publisher_name' resp. PTNA: 'ptna' - 'feed_publisher_name'">Publisher</a> (Owner)</th>
                            <th class="gtfs-date"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_start_date'">Valid from</a></th>
                            <th class="gtfs-date"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_end_date'">Valid until</a></th>
                            <th class="gtfs-number"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_version'">Version</a></th>
                            <th class="gtfs-date">Published</th>
                            <th class="gtfs-date">Download</th>
                            <th class="gtfs-text">Details (Licenses, ...)</th>
                        </tr>
