        <footer id="footer-it" class="clearing">
            <p>
                Tutti i dati geografici <a href="https://www.openstreetmap.org/copyright">© collaboratori di OpenStreetMap</a>.
            </p>
            <p>
                Questo programma è un software gratuito: puoi ridistribuirlo e / o modificarlo secondo i termini della <a href="https://www.gnu.org/licenses/gpl.html">LICENZA PUBBLICA GENERALE GNU, Versione 3, 29 giugno 2007</a> pubblicato dalla Free Software Foundation, versione 3 della Licenza o (a propria scelta) qualsiasi versione successiva. Ottieni il codice sorgente tramite <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
            <p>
                PTNA usa il <a href="https://wiki.openstreetmap.org/wiki/Overpass_API" title="Overpass-API">Overpass-API</a> per scaricare dati da OSM.
            </p>
            <p>
                Questa pagina è stata tradotta con l'aiuto di Google translate. I commenti per migliorare la traduzione sono benvenuti.
            </p>
        </footer>
