        <footer id="footer-es" class="clearing">
            <p>
                Totes les dades geogràfiques <a href="https://www.openstreetmap.org/copyright">© col·laboradors d'OpenStreetMap</a>.
            </p>
            <p>
                Aquest programa és programari lliure: pot redistribuir-lo i/o modificar-lo sota els termes de la <a href="https://www.gnu.org/licenses/gpl.html">LLICÈNCIA PÚBLICA GENERAL GNU, Versió 3, 29 de juny de 2007</a> segons publica la Free Software Foundation, ja sigui la versió 3 de la Llicència o (a la seva elección) qualsevol versió posterior.
                Obtenga el código fuente a través de <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
            <p>
                PTNA utilitza l'<a href="https://wiki.openstreetmap.org/wiki/Overpass_API" title="Overpass-API">Overpass-API</a> per a descarregar dades d'OSM. El servei Overpass-API és proporcionat per <a href="https://kumi.systems" title="Kumi Systems">Kumi Systems (Graz, Austria)</a>, gràcies pel seu recolçament.
            </p>
            <p>
                Els comentaris per a millorar la traducció de la pàgina són benvinguts.
            </p>
        </footer>
