        <footer id="footer-dk">
            <p>
                Alle geografiske data <a href="https://www.openstreetmap.org/copyright">© OpenStreetMap-bidragydere</a>.
            </p>
            <p>
                Dette program er gratis software: du kan omfordele det og / eller ændre det under betingelserne i <a href="https://www.gnu.org/licenses/gpl.html">GNU GENERAL PUBLIC LICENSE, version 3, 29. juni 2007</a> som offentliggjort af Free Software Foundation, enten version 3 af licensen eller (efter eget valg) enhver senere version. Hent kildekoden via <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
            <p>
                Denne side er oversat ved hjælp af Google translate. Kommentarer til forbedring af oversættelsen er velkomne.
            </p>
        </footer>

