                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Linje</a></th>
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Typen</a></th>
                            <th class="gtfs-date" colspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gyldighed</a></th>
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' eller 'route_desc' eller 'route_id'">Navn (eller beskrivelse eller Route-ID)</a></th>
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Agency</a> (Network/Operator)</th>
                            <th class="gtfs-name" colspan="1">PTNA info om linjen</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-date">Af</th>
                            <th class="gtfs-date">Til</th>
                            <th class="gtfs-comment">Kommentar</th>
                        </tr>
