                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2">Variant</th>
                            <th class="gtfs-name" rowspan="2">Trip-ID</th>
                            <th class="gtfs-name" colspan="3">Stops</th>
                            <th class="gtfs-name" colspan="1">PTNA info om varianten</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-text">Starten</th>
                            <th class="gtfs-text">Via</th>
                            <th class="gtfs-text">Ende</th>
<!--                            <th class="gtfs-checkbox">Ugyldig</th>
                            <th class="gtfs-checkbox">Defekt</th> -->
                            <th class="gtfs-comment">Kommentar</th>
                        </tr>
