                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" colspan="7">Stops</th>
                            <th class="gtfs-name" colspan="1">PTNA info om stop</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name">Nummer</th>
                            <th class="gtfs-name">Navn</th>
                            <th class="gtfs-name">Download</th>
                            <th class="gtfs-date">Afgangstid (1)</th>
                            <th class="gtfs-number">Latitude</th>
                            <th class="gtfs-number">Longitude</th>
                            <th class="gtfs-text">Stop-ID</th>
<!--                            <th class="gtfs-checkbox">Ugyldig</th>
                            <th class="gtfs-checkbox">Defekt</th> -->
                            <th class="gtfs-comment">Kommentar</th>
                        </tr>
