                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2">Navn</th>
                            <th class="gtfs-text" rowspan="2">Transportnet / Operatør / Område</th>
                            <th class="gtfs-name" colspan="7">GTFS-data</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-text"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_publisher_name' eller PTNA: 'ptna' - 'feed_publisher_name'">Udgiver</a> (Ejer)</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_start_date'">Gyldig fra</a></th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_end_date'">Gyldigt indtil</a></th>
                            <th class="gtfs-number"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_version'">Udgave</a></th>
                            <th class="gtfs-date">Offentliggørelse</th>
                            <th class="gtfs-date">Download</th>
                            <th class="gtfs-text">Detaljer (licenser, ...)</th>
                        </tr>
