                        <div style="border: 1px dotted gray; border-radius: 5px; padding: 0.5em;">
                                Legend:                                 &nbsp;
                                                                        </nobr><img src="/img/long-term19.png" width="19px" height="19px" title="long-term" />&nbsp;
                                Long term version (long-term)           </nobr>&nbsp;/&nbsp;
                                                                        </nobr><img src="/img/previous.svg" width="19px" height="19px" title="previous" />&nbsp;
                                Previous version (previous)             </nobr>&nbsp;/&nbsp;<nobr>
                                                                        </nobr><img src="/img/CheckMark.png" width="19px" height="19px" title="previous" />&nbsp;
                                PTNA's latest version                   </nobr>&nbsp;/&nbsp;<nobr>
                                                                        </nobr><img src="/img/error.svg" width="19px" height="19px" title="previous" />&nbsp;
                                Version with errors                     </nobr>&nbsp;/&nbsp;<nobr>
                                yyyy-mm-dd                              &nbsp;
                                Version date                            </nobr>&nbsp;/&nbsp;
                                                                        <nobr><span style="background-color: limegreen;">
                                yyyy-mm-dd</span>                       &nbsp;
                                Shown version                           </nobr>&nbsp;/&nbsp;
                                                                        <nobr><span style="background-color: lightgray; text-decoration: line-through;">
                                yyyy-mm-dd</span>                       &nbsp;
                                Missing version                         </nobr>
                        </div>
