                <p>
                    The first column contains a link to the analysis of the <a href="/en/gtfs-doc.php#gtfsdata">GTFS data</a>.
                    A symbol (<img src="/img/previous.svg" width="19px" height="19px"/>) indicates that the previous version of the GTFS data is available as well.
                    Another symbol (<img src="/img/long-term19.png" />) indicates that a long-term version of the GTFS data is also available.
                    This is usually the version of the GTFS data at the last official timetable change.
                </p>
                <p>
                    The GTFS data is checked almost daily for <a href="/en/gtfs-doc.php#download">up-to-dateness</a>.
                    However, not every available new version is analyzed and made available here - this would take up too much disk space.
                    In the column "Details (Licenses, ...)" the list of available GTFS data can be retrieved.
                </p>
