        <footer id="footer-tBR" class="clearing">
            <p>
                Todos os dados geográficos <a href="https://www.openstreetmap.org/copyright">© Contribuidores do OpenStreetMap</a>.
            </p>
            <p>
                Este programa é software livre: você pode redistribuí-lo e/ou modificá-lo sob os termos da <a href="https://www.gnu.org/licenses/gpl.html">GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007</a> conforme publicado pela Free Software Foundation, seja na versão 3 da Licença, ou (a seu critério) em qualquer versão posterior. Obtenha o código fonte através de <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
            <p>
                Esta página foi traduzida com a ajuda da <a href="https://www.deepl.com/translator">DeepL</a>. Comentários para melhorar a tradução são bem-vindos.
            </p>
        </footer>
