        <footer id="footer-tBR" class="clearing">
            <p>
                Todos os dados geográficos <a href="https://www.openstreetmap.org/copyright">© Colaboradores do OpenStreetMap</a>.
            </p>
            <p>
                Este programa é um software livre: você pode redistribuí-lo e/ou modificá-lo sob os termos da <a href="https://www.gnu.org/licenses/gpl.html">3ª versão de 29 de junho de 2007 da Licença Pública Geral GNU</a>, conforme publicado pela Free Software Foundation, seja a versão 3 da Licença, ou (a seu critério) qualquer versão posterior. O código deste programa está disponível no <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
        </footer>
