        <footer id="footer-tBR">
            <p>
                Todos os dados geográficos <a href="https://www.openstreetmap.org/copyright"> © colaboradores do OpenStreetMap </a>
            </p>
            <p>
                Este programa é um software gratuito: você pode redistribuí-lo e / ou modificá-lo sob os termos da <a href="https://www.gnu.org/licenses/gpl.html"> LICENÇA PÚBLICA GERAL GNU, Versão 3, 29 de junho de 2007 </a> conforme publicado pela Free Software Foundation, versão 3 da licença ou (a seu critério) qualquer versão posterior. Obtenha o código fonte no <a href="https://github.com/osm-ToniE"> GitHub </a>.
            </p>
            <p>
                Esta página foi traduzida para o português com a ajuda do Google translate. Comentários para melhorar a tradução são bem-vindos, especialmente para tradução correta para o português brasileiro.
            </p>
        </footer>

