                <p>
                    A primeira coluna contém um link para a análise dos <a href="/en/gtfs-doc.php#gtfsdata">dados GTFS</a>.
                    Um ícone (<img src="/img/previous.svg" width="19px" height="19px"/>) indica que uma versão mais antiga dos dados está disponível.
                    Este outro ícone (<img src="/img/long-term19.png" />) indica que uma versão de longo prazo dos dados está disponível.
                    Geralmente esta é a versão mais recente dos dados GTFS que contém as últimas alterações nos quadros de horários.
                </p>
                <p>
                    Os dados GTFS são verificados quase diariamente para <a href="/en/gtfs-doc.php#download">atualidade</a>.
                    Entretanto, nem toda nova versão disponível é analisada e disponibilizada aqui - isto ocuparia muito espaço em disco.
                    Na coluna "Detalhes (licenças, entre outros)" você pode ver a lista de dados GTFS disponíveis.
                </p>
