                <p>
                    A primeira coluna contém um link para a análise dos <a href="/en/gtfs-doc.php#gtfsdata">dados GTFS</a>.
                    Um ícone (<img src="/img/previous.svg" width="19px" height="19px"/>) indica que uma versão mais antiga dos dados está disponível.
                    Este outro ícone (<img src="/img/long-term19.png" />) indica que uma versão de longo prazo dos dados está disponível.
                    Geralmente esta é a versão mais recente dos dados GTFS que contém as últimas alterações nos quadros de horários.
                </p>
                <p>
                    A <a href="/en/gtfs-doc.php#download">atualização</a> dos dados desta página ocorre em intervalos irregulares.
                </p>
