                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Linha</a></th>
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Tipo</a></th>
                            <th class="gtfs-date" colspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' and 'end_date'">Vigência</a></th>
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' resp. 'route_desc' resp. 'route_id'">Nome (resp. description, resp. Route-ID)</a></th>
                            <th class="gtfs-name" rowspan="2"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Agência</a> (rede ou operador)</th>
                            <th class="gtfs-name" colspan="1">Informações do PTNA sobre a linha</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-date">De</th>
                            <th class="gtfs-date">Até</th>
                            <th class="gtfs-comment">Observação</th>
                        </tr>
