        <footer id="footer-es" class="clearing">
            <p>
                Todos los datos geográficos <a href="https://www.openstreetmap.org/copyright">© colaboradores de OpenStreetMap</a>.
            </p>
            <p>
                Este programa es software libre: puede redistribuirlo y / o modificarlo bajo los términos de la <a href="https://www.gnu.org/licenses/gpl.html">LICENCIA PÚBLICA GENERAL GNU, Versión 3, 29 de junio de 2007</a> según lo publicado por la Free Software Foundation, ya sea la versión 3 de la Licencia o (a su elección) cualquier versión posterior.
                Obtenga el código fuente a través de <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
            <p>
                PTNA utiliza la <a href="https://wiki.openstreetmap.org/wiki/Overpass_API" title="Overpass-API">Overpass-API</a> para descargar datos de OSM. El servicio Overpass-API es proporcionado por <a href="https://kumi.systems" title="Kumi Systems">Kumi Systems (Graz, Austria)</a>, gracias por el apoyo.
            </p>
            <p>
                Esta página ha sido traducida al español con la ayuda de Google translate.
                Los comentarios para mejorar la traducción son bienvenidos.
            </p>
        </footer>
