                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-routeshortname"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Route</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Type</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://wiki.openstreetmap.org/wiki/Relation:route#Public_transport_routes" title="Proposal for OSM mapping">OSM route</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' and 'end_date'">Valid from</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' and 'end_date'">Valid until</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' resp. 'route_desc' resp. 'route_id'">Name (resp. description, resp. Route-ID)</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Agency</a> (Network/Operator)&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name">PTNA info&nbsp;&nbsp;&nbsp;&nbsp;</th>
                        </tr>
