                <p>
                    The first column contains a link to the analysis of the <a href="/en/gtfs-doc.php#gtfsdata">GTFS data</a>.
                    A symbol (<img src="/img/previous.svg" width="19px" height="19px"/>) indicates that the previous version of the GTFS data is available as well.
                    Another symbol (<img src="/img/long-term19.png" />) indicates that a long-term version of the GTFS data is also available.
                    This is usually the version of the GTFS data at the last official timetable change.
                </p>
                <p>
                    Los datos del GTFS se comprueban casi a diario para <a href="/en/gtfs-doc.php#download">actualización</a>.
                    Sin embargo, no todas las nuevas versiones disponibles son analizadas y puestas a disposición aquí - esto ocuparía demasiado espacio en el disco.
                    En la columna "Detalles (Licencias, ...)" se puede ver la lista de datos GTFS disponibles.
                </p>
