                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name"    rowspan="2">Variant</th>
                            <th class="gtfs-name"    rowspan="2">Trip-ID</th>
                            <th class="gtfs-comment" rowspan="2">Número de paseos</th>
                            <th class="gtfs-name"    colspan="2">Valid</th>
                            <th class="gtfs-name"    colspan="3">Stops</th>
                            <th class="gtfs-comment" colspan="1">PTNA info</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-date">From</th>
                            <th class="gtfs-date">Until</th>
                            <th class="gtfs-text">Start</th>
                            <th class="gtfs-text">Via</th>
                            <th class="gtfs-text">End</th>
                            <th class="gtfs-comment">Comment</th>
                        </tr>
