                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-none"    colspan="3">&nbsp;</th>
                            <th class="gtfs-name js-sort-none"    colspan="1">Direction</th>
                            <th class="gtfs-name js-sort-none"    colspan="2">Valid</th>
                            <th class="gtfs-name js-sort-none"    colspan="3">Stops</th>
                            <th class="gtfs-comment js-sort-none" colspan="1">PTNA info</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-number">&#x21C5;Variant</th>
                            <th class="gtfs-name js-sort-string">&#x21C5;Trip-ID</th>
                            <th class="gtfs-comment js-sort-triprides">&#x21C5;Number of rides</th>
                            <th class="gtfs-text js-sort-number">&#x21C5;Outbound (=0) / Inbound (=1)</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;From</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Until</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Start</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Via</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;End</th>
                            <th class="gtfs-comment js-sort-string">&#x21C5;Comment</th>
                        </tr>
