                <p>
                    The first column contains a link to the analysis of the <a href="/en/gtfs-doc.php#gtfsdata">GTFS data</a>.
                    <ul style="list-style: none;">
                        <li> <img src="/img/long-term19.png" /> : indicates that a long-term version of the GTFS data is also available.
                             This is usually the version of the GTFS data at the last official timetable change.</li>
                        <li> <img src="/img/previous.svg" width="19px" height="19px"/> : indicates that a previous version of the GTFS data is available as well.</li>
                        <li> <img src="/img/compare19.png" width="19px" height="19px"/> : indicates that two versions can be compared (beta status: not imlemented in all details)</li>
                    </ul>
                </p>
                <p>
                    Los datos del GTFS se comprueban casi a diario para <a href="/en/gtfs-doc.php#download">actualización</a>.
                    Sin embargo, no todas las nuevas versiones disponibles son analizadas y puestas a disposición aquí - esto ocuparía demasiado espacio en el disco.
                    En la columna "Detalles (Licencias, ...)" se puede ver la lista de datos GTFS disponibles.
                </p>
