        <footer id="footer-id" class="clearing">
            <p>
                Semua data geografis <a href="https://www.openstreetmap.org/copyright">© kontributor OpenStreetMap</a>.
            </p>
            <p>
                Program ini adalah perangkat lunak bebas: Anda dapat mendistribusikannya dan/atau memodifikasinya sesuai dengan ketentuan lisensi <a href="https://www.gnu.org/licenses/gpl.html">GNU GENERAL PUBLIC LICENSE, Version 3, 29 Juni 2007</a> sebagaimana diterbitkan oleh Free Software Foundation, baik versi 3 dari Lisensi, atau (sesuai pilihan Anda) versi yang lebih baru. Dapatkan kode sumber melalui <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
            <p>
                PTNA menggunakan <a href="https://wiki.openstreetmap.org/wiki/Overpass_API" title="Overpass API">Overpass API</a> untuk mengunduh data dari OSM.
            </p>
        </footer>
