                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-none"    colspan="3">&nbsp;</th>
                            <th class="gtfs-name js-sort-none"    colspan="1">Arah</th>
                            <th class="gtfs-name js-sort-none"    colspan="2">Berlaku</th>
                            <th class="gtfs-name js-sort-none"    colspan="3">Halte-halte</th>
                            <th class="gtfs-comment js-sort-none" colspan="1">Info PTNA </th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-number">&#x21C5;Varian</th>
                            <th class="gtfs-name js-sort-string">&#x21C5;Pengidentifikasi perjalanan</th>
                            <th class="gtfs-comment js-sort-triprides">&#x21C5;Nomor pengendara</th>
                            <th class="gtfs-text js-sort-number">&#x21C5;Keluar (=0) / Masuk (=1)</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Dari</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Hingga</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Awal</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Lewat</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Akhir</th>
                            <th class="gtfs-comment js-sort-string">&#x21C5;Komentar</th>
                        </tr>
