                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-routename">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Trayek</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Jenis</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://wiki.openstreetmap.org/wiki/Relation:route#Public_transport_routes" title="Proposal for OSM mapping">Trayek OSM</a></th>
                            <th class="gtfs-date">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' and 'end_date'">Berlaku dari</a></th>
                            <th class="gtfs-date">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' and 'end_date'">Berlaku hingga</a></th>
                            <th class="gtfs-name js-sort-routename">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' resp. 'route_desc' resp. 'route_id'">Nama (deskripsi atau identifikasi rute masing-masing)</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://gtfs.org/schedule/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Badan/Perusahaan</a> (Jaringan/Operator)</th>
                            <th class="gtfs-name">&#x21C5;Info PTNA</th>
                        </tr>
