                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2">Nama</th>
                            <th class="gtfs-text" rowspan="2">Jaringan / Operator / Cakupan</th>
                            <th class="gtfs-name" colspan="7">Data GTFS</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-text"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_publisher_name' resp. PTNA: 'ptna' - 'feed_publisher_name'">Penerbit</a> (Pemilik)</th>
                            <th class="gtfs-date"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_start_date'">Berlaku dari</a></th>
                            <th class="gtfs-date"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_end_date'">Berlaku hingga</a></th>
                            <th class="gtfs-number"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_version'">Versi</a></th>
                            <th class="gtfs-date">Published</th>
                            <th class="gtfs-date">Download</th>
                            <th class="gtfs-text">Details (Licenses, ...)</th>
                        </tr>
