                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-routename">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Linje</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Typen</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://wiki.openstreetmap.org/wiki/Relation:route#Public_transport_routes" title="Forslag til OSM-kortlægning">OSM route</a></th>
                            <th class="gtfs-date">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gyldig af</a></th>
                            <th class="gtfs-date">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gyldig til</a></th>
                            <th class="gtfs-name js-sort-routename">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' eller 'route_desc' eller 'route_id'">Navn (eller beskrivelse eller Route-ID)</a></th>
                            <th class="gtfs-name">&#x21C5;<a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Agency</a> (Network/Operator)</th>
                            <th class="gtfs-name">&#x21C5;PTNA info</th>
                        </tr>
