                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-none"    colspan="3">&nbsp;</th>
                            <th class="gtfs-name js-sort-none"    colspan="2">Gyldighed</th>
                            <th class="gtfs-name js-sort-none"    colspan="3">Stops</th>
                            <th class="gtfs-comment js-sort-none" colspan="1">PTNA info om varianten</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-number">&#x21C5;Variant</th>
                            <th class="gtfs-name js-sort-string">&#x21C5;Trip-ID</th>
                            <th class="gtfs-comment js-sort-triprides">&#x21C5;Antal ture</th>
                            <th class="gtfs-date js-sort-string">&#x21C5;Af</th>
                            <th class="gtfs-date js-sort-string">&#x21C5;Til</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Starten</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Via</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Ende</th>
                            <th class="gtfs-comment js-sort-string">&#x21C5;Kommentar</th>
                        </tr>
