                <p>
                    Den første kolonne i tabellen indeholder et link til en evaluering af <a href="/da/gtfs-doc.php#gtfsdata">GTFS-data</a>.
                    Et symbol (<img src="/img/previous.svg" width="19px" height="19px"/>) angiver, at den tidligere version af GTFS-dataene også er tilgængelig.
                    Et andet symbol (<img src="/img/long-term19.png" />) angiver, at en langvarig version af GTFS-data også er tilgængelig.
                    Dette er normalt versionen af GTFS-data ved den sidste officielle tidsplanændring.
                </p>
                <p>
                    <a href="/da/gtfs-doc.php#download">Opdateringen</a> af dataene på denne side finder sted med uregelmæssige intervaller.
                </p>
