                <p>
                    Den første kolonne i tabellen indeholder et link til en evaluering af <a href="/da/gtfs-doc.php#gtfsdata">GTFS-data</a>.
                    <ul style="list-style: none;">
                        <li> <img src="/img/long-term19.png" /> : angiver, at en langvarig version af GTFS-data også er tilgængelig.
                             Dette er normalt versionen af GTFS-data ved den sidste officielle tidsplanændring</li>
                        <li> <img src="/img/previous.svg" width="19px" height="19px"/> : angiver, at en tidligere version af GTFS-dataene også er tilgængelig.</li>
                        <li> <img src="/img/compare19.png" width="19px" height="19px"/> : angiver, at to versioner kan sammenlignes (beta-status: ikke implementeret i alle detaljer)</li>
                    </ul>
                </p>
                <p>
                    GTFS-dataene kontrolleres næsten dagligt for <a href="/de/gtfs-doc.php#download">aktualitet</a>.
                    Imidlertid er ikke alle tilgængelige nye versioner analyseret og gjort tilgængelige her - det ville belaste lagerpladsen for meget.
                    Listen over tilgængelige GTFS-data kan hentes i kolonnen "Detaljer (licenser, ...)".
                </p>
