                <p>
                    Den første kolonne i tabellen indeholder et link til en evaluering af <a href="/da/gtfs-doc.php#gtfsdata">GTFS-data</a>.
                    Et kalenderikon angiver, at den tidligere version af GTFS-dataene også er tilgængelig.
                </p>
                <p>
                    <a href="/da/gtfs-doc.php#download">Opdateringen</a> af dataene på denne side finder sted med uregelmæssige intervaller.
                </p>
