                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-routename"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_short_name'">Linje</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/extended-route-types" title="GTFS spec: extended route types">Typen</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://wiki.openstreetmap.org/wiki/Relation:route#Public_transport_routes" title="Forslag til OSM-kortlægning">OSM route</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gyldig af</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#calendartxt" title="GTFS spec: 'calendar.txt' - 'start_date' und 'end_date'">Gyldig til</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name js-sort-routename"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#routestxt" title="GTFS spec: 'routes.txt' - 'route_long_name' eller 'route_desc' eller 'route_id'">Navn (eller beskrivelse eller Route-ID)</a>&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#agencytxt" title="GTFS spec: 'agency.txt' - 'agency_name'">Agency</a> (Network/Operator)&nbsp;&nbsp;&nbsp;&nbsp;</th>
                            <th class="gtfs-name">PTNA info&nbsp;&nbsp;&nbsp;&nbsp;</th>
                        </tr>
