                            <tr class="gtfs-tableheaderrow">
                                <th class="gtfs-name js-sort-routename">&#x21C5;Route</th>
                                <th class="gtfs-name">&#x21C5;OSM route</th>
                                <th class="gtfs-name">&#x21C5;PTNA</th>
                                <th class="gtfs-name">&#x21C5;Information</th>
                            </tr>
