                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2">Nome</th>
                            <th class="gtfs-text" rowspan="2">Rede, operador(a) e/ou cobertura</th>
                            <th class="gtfs-name" colspan="7">Dados GTFS</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-text"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_publisher_name' resp. PTNA: 'ptna' - 'feed_publisher_name'">Distribuido por</a> (proprietário)</th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_start_date'">Início de vigência</a></th>
                            <th class="gtfs-date"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_end_date'">Válido até</a></th>
                            <th class="gtfs-number"><a target="_blank" href="https://developers.google.com/transit/gtfs/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_version'">Versão</a></th>
                            <th class="gtfs-date">Publicado em</th>
                            <th class="gtfs-date">Baixaado em</th>
                            <th class="gtfs-text">Detalhes (licenças, entre outros)</th>
                        </tr>
