                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-none"    colspan="3">&nbsp;</th>
                            <th class="gtfs-name js-sort-none"    colspan="1">Direction</th>
                            <th class="gtfs-name js-sort-none"    colspan="2">Vigência</th>
                            <th class="gtfs-name js-sort-none"    colspan="3">Pontos</th>
                            <th class="gtfs-comment js-sort-none" colspan="1">Informações do PTNA</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name js-sort-number">&#x21C5;Variante</th>
                            <th class="gtfs-name js-sort-string">&#x21C5;ID do trajeto</th>
                            <th class="gtfs-comment js-sort-triprides">&#x21C5;Número de passeios</th>
                            <th class="gtfs-text js-sort-number">&#x21C5;Outbound (=0) / Inbound (=1)</th>
                            <th class="gtfs-date js-sort-string">&#x21C5;De</th>
                            <th class="gtfs-date js-sort-string">&#x21C5;Até</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Inicial</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Via</th>
                            <th class="gtfs-text js-sort-string">&#x21C5;Final</th>
                            <th class="gtfs-comment js-sort-string">&#x21C5;Observação</th>
                        </tr>
