                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name"    rowspan="2">Variante</th>
                            <th class="gtfs-name"    rowspan="2">ID do trajeto</th>
                            <th class="gtfs-comment" rowspan="2">Número de passeios</th>
                            <th class="gtfs-name"    colspan="2">Vigência</th>
                            <th class="gtfs-name"    colspan="3">Pontos</th>
                            <th class="gtfs-comment" colspan="1">Informações do PTNA</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-date">De</th>
                            <th class="gtfs-date">Até</th>
                            <th class="gtfs-text">Inicial</th>
                            <th class="gtfs-text">Via</th>
                            <th class="gtfs-text">Final</th>
                            <th class="gtfs-comment">Observação</th>
                        </tr>
