        <header id="headerblock">
            <div id="headerimg" class="logo">
                <a href="/"><img src="/img/logo.png" alt="logo" /></a>
            </div>
            <div id="headertext">
                <h1><a href="/">PTNA - Public Transport Network Analysis</a></h1>
                <h2>Análise Estática para OpenStreetMap</h2>
            </div>
            <div id="headernav">
                <a href="/">Início</a> |
                <a href="/contact.html">Contato</a> |
                <a target="_blank" href="https://www.openstreetmap.de/impressum.html">Impressão</a> |
                <a target="_blank" href="https://www.fossgis.de/datenschutzerklärung">Política de privacidade</a> |
                <a href="/en/index.html" title="english"><img src="/img/GreatBritain16.png"  class="flagimg" alt="Union Jack" /></a>
                <a href="/de/index.html" title="deutsch"><img src="/img/Germany16.png"  class="flagimg" alt="deutsche Flagge" /></a>
                <a href="/fr/index.html" title="français"><img src="/img/France16.png"  class="flagimg" alt="drapeau français" /></a>
            </div>
        </header>
