        <footer id="footer-fr" class="clearing">
            <p>
                Toutes les données géographiques <a href="https://www.openstreetmap.org/copyright"> © OpenStreetMap contributors </a>.
            </p>
            <p>
                Ce programme est un logiciel libre : vous pouvez le redistribuer et / ou le modifier selon les termes de la <a href="https://www.gnu.org/licenses/gpl.html"> LICENCE PUBLIQUE GÉNÉRALE GNU, Version 3, 29 juin 2007 </a> telle que publiée par la Free Software Foundation, version 3 de la licence ou (à votre choix) toute version ultérieure.
                Obtenez le code source via <a href="https://github.com/osm-ToniE"> GitHub </a>.
            </p>
        </footer>
