                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-name" rowspan="2">Namn</th>
                            <th class="gtfs-text" rowspan="2">Nätverk / Operatör / Täckning</th>
                            <th class="gtfs-name" colspan="7">GTFS-data</th>
                        </tr>
                        <tr class="gtfs-tableheaderrow">
                            <th class="gtfs-text"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_publisher_name' resp. PTNA: 'ptna' - 'feed_publisher_name'">Utgivare</a> (Ägare)</th>
                            <th class="gtfs-date"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_start_date'">Giltig från</a></th>
                            <th class="gtfs-date"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_end_date'">Giltig till och med</a></th>
                            <th class="gtfs-number"><a target="_blank" href="https://gtfs.org/schedule/reference/#feed_infotxt" title="GTFS: 'feed_info.txt' - 'feed_version'">Version</a></th>
                            <th class="gtfs-date">Publicerad</th>
                            <th class="gtfs-date">Nedladdning</th>
                            <th class="gtfs-text">Detaljer (Licenser, ...)</th>
                        </tr>
