                <p>
                    I den första kolumnen finns en länk till analysen av <a href="/en/gtfs-doc.php#gtfsdata">GTFS-data</a>.
                    <ul style="list-style: none;">
                        <li> <img src="/img/long-term19.png" /> : anger att en långtidsversion av GTFS-data också finns tillgänglig.
                             Detta är vanligtvis den version av GTFS-data som gällde vid det senaste officiella tidtabellsskiftet.</li>
                        <li> <img src="/img/previous.svg" width="19px" height="19px"/> : anger att en tidigare version av GTFS-data också finns tillgänglig.</li>
                        <li> <img src="/img/compare19.png" width="19px" height="19px"/> : anger att två versioner kan jämföras (betastatus: inte implementerad i alla detaljer)</li>
                    </ul>
                </p>
                <p>
                    GTFS-uppgifterna kontrolleras nästan dagligen för <a href=A/sv/gtfs-doc.php#download">aktualitet</a>.
                    Alla tillgängliga nya versioner analyseras dock inte och görs tillgängliga här - detta skulle ta upp för mycket diskutrymme.
                    I kolumnen ”Detaljer (Licenser, ...)” kan listan över tillgängliga GTFS-data hämtas.
                </p>
