        <footer id="footer-sv" class="clearing">
            <p>
                Alla GTFS-data © ägare av GTFS-data.
            </p>
            <p>
                Alla geografiska data <a href="https://www.openstreetmap.org/copyright">© bidragsgivare till OpenStreetMap</a>.
            </p>
            <p>
                Det här programmet är fri programvara: du kan vidaredistribuera det och/eller modifiera det enligt villkoren i <a href="https://www.gnu.org/licenses/gpl.html">GNU GENERAL PUBLIC LICENSE, Version 3, 29 June 2007</a> som publiceras av Free Software Foundation, antingen version 3 av licensen eller (efter eget val) någon senare version. Hämta källkoden via <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
        </footer>
