        <footer id="footer-sr" class="clearing">
            <p>
                Сви географски подаци <a href="https://www.openstreetmap.org/copyright">© сарадници OpenStreetMap</a>.
            </p>
            <p>
                Овај програм је бесплатан софтвер: можете га дистрибуирати и / или модификовати под условима из <a href="https://www.gnu.org/licenses/gpl.html">GNU GENERAL PUBLIC LICENSE, Version 3, 29 јуна 2007</a> у издању Фондације за слободни софтвер, било верзије 3 лиценце, или (по вашој жељи) било које касније верзије. Набавите изворни код путем <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
            <p>
                ПТНА користи <a href="https://wiki.openstreetmap.org/wiki/Overpass_API" title="Overpass-API">Overpass-API</a> за преузимање података из OSM-а. Услугу АПИ надвожњака пружа <a href="https://kumi.systems" title="Kumi Systems">Куми Системс (Грац, Аустрија)</a>, хвала на подршци.
            </p>
        </footer>
