        <footer id="footer-sr" class="clearing">
            <p>
                Сви ГТФС подаци © власник ГТФС података.
            </p>
            <p>
                Сви географски подаци <a href="https://www.openstreetmap.org/copyright">© сарадници OpenStreetMap</a>.
            </p>
            <p>
                Овај програм је бесплатан софтвер: можете га дистрибуирати и / или модификовати под условима из <a href="https://www.gnu.org/licenses/gpl.html">GNU GENERAL PUBLIC LICENSE, Version 3, 29 јуна 2007</a> у издању Фондације за слободни софтвер, било верзије 3 лиценце, или (по вашој жељи) било које касније верзије. Набавите изворни код путем <a href="https://github.com/osm-ToniE">GitHub</a>.
            </p>
        </footer>
